name: BlockEffect
version: ${project.version}
main: com.bilastend.blockeffect.Main
api-version: 1.16
authors: [ Bilastend ]
description: Get a random effect on different block types
website: github.com/Bilastend

commands:
  blockeffect:
    permission: blockeffect.commands.blockeffect
